geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoriesListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    path('register/', authapp.register, name='register'),
    path('profile/', authapp.edit, name='edit'),

    # path('profile/<int:pk>/', authapp.Edit.as_view(template_name='authapp/edit.html'), name='edit'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),

]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='list'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/geekshop/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import urls
from . import settings
from .views import contact, main

app_name = 'geekshop'

urlpatterns = [
    path('', main, name='index'),
    path('admin/', admin.site.urls),
    path('contact/', contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('__debug__/', include(debug_toolbar.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>', product, name='product'),

]

geekshop/geekshop/views.py
from django.shortcuts import render
from mainapp.models import Product, ProductCategory

from basketapp.models import Basket


def main(request):

    # products = Product.objects.all()[:3]
    products = Product.objects.filter().select_related('category')[:3]


    basket=''
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    context = {
        'slogan': 'Мега-удобные стулья',
        'topic': 'Тренды',
        'products': products,
        'basket': basket,

    }
    return render(request, 'index.html', context=context)

def contact(request):
    return render(request, 'contact.html')

geekshop/geekshop/templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
	<meta charset="utf-8">
	<title>
		{% block title %}
			{{ title|title }}
		{% endblock %}
	</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">

	{% block css %}
	{% endblock %}

	{% block js %}
	{% endblock %}

</head>
<body>
	<div class="container">

        {% block main_slider %}
        {% endblock %}

        {% block featured%}
        {% endblock %}

		{% block content %}
		{% endblock %}

		<div class="clr"></div>

	</div>

    {% include 'inc_footer.html' %}

</body>
</html>

geekshop/geekshop/templates/contact.html
{% extends 'base.html' %}


{%load static%}

{% block main_slider %}
	<div class="hero">
		{% include 'inc_menu.html' %}

			<h1>наши контакты</h1>
	</div>
{%endblock%}

{% block content %}
	<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>
{% endblock %}

geekshop/geekshop/templates/inc_footer.html
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB 2017</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
</div>

geekshop/geekshop/templates/inc_menu.html
<div class="header clearfix">
    <a href="index.html" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'index'%}" class="{% if request.resolver_match.route == '' %}
               active
            {% endif %}">домой</a></li>
        <li><a href="{% url 'products:category' 0 %}" class="{% if request.resolver_match.route == 'products/' %}
                active
                {% endif %}">продукты</a></li>
        <li><a href="{% url 'contact'%}" class="{% if request.resolver_match.route == 'contact/' %}
                active
                {% endif %}">контакты</a></li>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'auth:edit'  %}">
                    {{ user.first_name|default:'Пользователь' }}
                </a>
            </li>
        {% endif %}
        {% if user.is_superuser %}
          <li>
              <a href="{% url 'admin_staff:users' %}">
                  админка
              </a>
          </li>
        {% endif %}
            <li>
                <a href="{% url 'order:list' %}">заказы</a>
                {% if user.is_authenticated %}
                  <a href="{% url 'auth:logout' %}">выйти</a>
                {% else %}
                  <a href="{% url 'auth:login' %}">войти</a>
                {% endif %}
            </li>
    </ul>
    {% if basket %}
        <a href="{% url 'basket:list' %}" class="fa fa-shopping-basket">
            <span>
                {% if basket %}
                    {{ basket.0.total_cost|floatformat:0 }} руб
                    ({{ basket.0.total_quantity }} шт.)
                {% endif %}
            </span>
        </a>
    {% endif %}
    <a href="#" class="search"></a>
</div>

geekshop/geekshop/templates/index.html
{% extends 'base.html'%}

{% load static %}

{% block main_slider %}
		<div class="slider">
			{% include 'inc_menu.html' %}
			<div class="text-slider">
				<h3 class="green">{{topic}} {% now "Y" %}</h3>
				<h3 class="big"> {{slogan}}</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{%static 'img/arrow.png'%}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>
{% endblock %}

{% block featured%}
		<div class="featured">
			<div class="featured-menu">
				<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{%static 'img/arrow.png'%}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% for product in products %}
					<div class="block">
						<a href="#"><img src="/media/{{product.image}}" alt="">
							<div class="text">
								<img src="{%static 'img/icon-hover.png'%}" alt="img">
								<h4>{{product.name}}</h4>
								<p>{{product.short_desc}} </p>
							</div>
						</a>
					</div>
				{%endfor%}
			</div>
		</div>
{% endblock %}