geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    path('register/', authapp.register, name='register'),
    path('profile/', authapp.edit, name='edit'),

    # path('profile/<int:pk>/', authapp.Edit.as_view(template_name='authapp/edit.html'), name='edit'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),

]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='list'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/geekshop/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import urls
from . import settings
from .views import contact, main

app_name = 'geekshop'

urlpatterns = [
    path('', main, name='index'),
    path('admin/', admin.site.urls),
    path('contact/', contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('__debug__/', include(debug_toolbar.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>', product, name='product'),

]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        max_length=64,
        unique=True,
        verbose_name='имя'
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    updated = models.DateTimeField(
        auto_now=True
    )

    is_active = models.BooleanField(
        default=True
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        verbose_name='категория',
        on_delete=models.CASCADE,
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )

    image = models.ImageField(
        upload_to='products_img',
        blank=True,
    )


    short_desc = models.CharField(
        max_length=256,
        verbose_name='краткое описание',
        blank=True,
    )

    description = models.TextField(
        verbose_name='описание продукта',
        blank=True,
        max_length=500,
    )

    price = models.DecimalField(
        verbose_name='цена продукта',
        max_digits=8,
        decimal_places=2,
        default=0,
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )

    is_active = models.BooleanField(
        default=True
    )

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop/mainapp/views.py
import random

from basketapp.models import Basket
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from mainapp.models import ProductCategory, Product


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.all()
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.all()


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_hot_product():
    products = Product.objects.all()

    return random.sample(list(products), 1)[0]

def get_same_products(hot_products):
    same_products = Product.objects.filter(category=hot_products.category).exclude(pk=hot_products.pk)[:3]

    return same_products
#
# def products(request, pk=None, page=1):
#     title = 'продукты'
#     category = ''
#     products = ''
#     # links_menu = ProductCategory.objects.all()
#
#     categories = ProductCategory.objects.all()
#     # basket = get_basket(request.user)
#
#     if pk:
#         if pk == 0:
#             category = {
#                 'pk': 0,
#                 'name': 'Все'
#             }
#         else:
#             category = get_object_or_404(ProductCategory, pk=pk)
#             # products = Product.objects.filter(category_id__pk=pk).order_by('price')
#             products = Product.objects.filter(category_id__pk=pk).select_related().order_by('price')
#
#
#         paginator=Paginator(products, 2)
#         try:
#             products_paginator=paginator.page(page)
#         except PageNotAnInteger:
#             products_paginator=paginator.page(1)
#         except EmptyPage:
#             products_paginator=paginator.page(paginator.num_pages)
#
#
#     hot_product = get_hot_product()
#     same_products = get_same_products(hot_product)
#
#     context = {
#         'title': title,
#         'categories': categories,
#         'category': category,
#         'links_menu': get_links_menu(),
#         'products': products_paginator,
#         # 'basket': basket,
#         'hot_product': hot_product,
#         'same_products': same_products,
#     }
#     return render(request, 'products_list.html', context=context)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []

def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)
    basket = get_basket(request.user)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    if pk:
        if pk == '0':
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                'price')

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'hot_product': hot_product,
            'category': category,
            'products': products_paginator,
            'basket': basket,
        }

        return render(request, 'products_list.html', content)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': basket,
    }

    return render(request, 'products.html', content)


@login_required
def product(request, pk):
    title = 'страница продукта'
    # product: get_object_or_404(Product, pk=pk)

    product = get_product(pk)

    context = {
        'title': title,
        'product': product,
        'links_menu': get_links_menu(),
        # 'basket': get_basket(request.user),
        # 'categories': ProductCategory.objects.all(),
        'categories': ProductCategory.objects.filter().select_related()

    }

    return render(request, 'product.html', context)

geekshop/mainapp/templates/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:category' 0 %}"
           class = "{% if request.resolver_match.kwargs.pk == '0' %}
                    active
                    {% endif %}">
            все
        </a>

    </li>
        {% for link in links_menu %}
            <li>
                <a href="{% url 'products:category' link.pk %}"
                   class = "{% if request.resolver_match.kwargs.pk == link.pk %}
                            active
                            {% endif %}">
                        {{ link.name }}
                    </a>
                </li>
            {% endfor %}
</ul>

geekshop/mainapp/templates/product.html
{% extends 'base.html' %}

{%load static%}

{% block main_slider %}
<div class="container">
	<div class="hero-white">
		{% include 'inc_menu.html' %}
	</div>
{% endblock %}
{% block content %}
	<div class="details">
		<div class="links clearfix">
			{% include 'inc_categories_menu.html' %}
		</div>
		<div class="row my-5">
			<div class="col-6">
				<div class="slider-product">
					<img src="/media/{{ product.image }}" class="w-100">
				</div>
				<div class="slider-control ml-2 my-3">
					<div class="block">
						<a href="#"><img src="/media/{{ product.image }}" alt=""></a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{ product.image }}" alt=""></a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{ product.image }}" alt=""></a>
					</div>
				</div>
			</div>
			<div class="col-6">
				<h3 class="big-bold">{{ product.name}}</h3>
<!--				<h3 class="red">горячее предложение</h3>-->
				<p class="price">{{ product.price }} <span>руб</span></p>
				<a href="{% url 'basket:add' product.pk %}" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					{{ product.description }}
				</div>
			</div>
		</div>

		<div class="related">
			<div class="title clearfix">
				<h2>Похожие продукты</h2>
				<a class="explore" href="#">показать все <img src="{%static 'img/arrow.png'%}" alt=""></a>
			</div>
			<div class="related-products clearfix">
				<div class="block">
					<a href="#"><img src="{%static 'img/product-11.jpg'%}" alt="">
						<div class="text">
							<img src="{%static 'img/icon-hover.png'%}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{%static 'img/product-21.jpg'%}" alt="">
						<div class="text">
							<img src="{%static 'img/icon-hover.png'%}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{%static 'img/product-31.jpg'%}" alt="">
						<div class="text">
							<img src="{%static 'img/icon-hover.png'%}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>

			</div>
		</div>
	</div>
		</div>

{% endblock %}

geekshop/mainapp/templates/products.html
{% extends 'base.html' %}

{%load static%}

{% block main_slider %}
<div class="container">
	<div class="hero-white">
		{% include 'inc_menu.html' %}

	</div>
	</div>
{% endblock %}


{%block content%}
	<div class="details">
		<div class="links clearfix">
			{% include 'inc_categories_menu.html' %}
		</div>

		<div class="details-products">
			<div class="details-slider">
				<div class="slider-product">
					<img src="{%static 'img/slider1.jpg'%}">
				</div>
				<div class="slider-control">
					<div class="block">
						<a href="#"><img src="{%static 'img/controll.jpg'%}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{%static 'img/controll1.jpg'%}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{%static 'img/controll2.jpg'%}" alt="">
							<div class="text"></div>
						</a>
					</div>
				</div>
			</div>

			<div class="description">
				<h3 class="big-bold">Отличный стул</h3>
				<h3 class="red">горячее предложение</h3>
				<p class="price"> 2585.9 <span>руб</span></p>
				<a href="#" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					<p>Расположитесь комфортно.</p>
					<p>Отличное качество материалов
						позволит вам это.</p>
					<p>Различные цвета</p>
					<p>высочайший уровень
						эргономики и прочность.</p>
				</div>
			</div>
		</div>

		<div class="related">
			<div class="title clearfix">
				<h2>Похожие продукты</h2>
				<a class="explore" href="#">показать все <img src="{%static 'img/arrow.png'%}" alt=""></a>
			</div>
			<div class="related-products clearfix">
				<div class="block">
					<a href="#"><img src="{%static 'img/product-11.jpg'%}" alt="">
						<div class="text">
							<img src="{%static 'img/icon-hover.png'%}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{%static 'img/product-21.jpg'%}" alt="">
						<div class="text">
							<img src="{%static 'img/icon-hover.png'%}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{%static 'img/product-31.jpg'%}" alt="">
						<div class="text">
							<img src="{%static 'img/icon-hover.png'%}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>

			</div>
		</div>
	</div>
{% endblock %}

geekshop/mainapp/templates/products_list.html
{% extends 'base.html' %}

{%load static%}

{% block main_slider %}
<div class="container">
	<div class="hero-white">
		{% include 'inc_menu.html' %}
	</div>
{% endblock %}
{% block content %}
	<div class="details">
		<div class="links clearfix">
			{% include 'inc_categories_menu.html' %}
		</div>
		<div class="row my-5">
			<div class="col-6">
				<div class="slider-product">
					<img src="/media/{{ hot_product.image }}" class="w-100">
				</div>
				<div class="slider-control ml-2 my-3">
					<div class="block">
						<a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
					</div>
				</div>
			</div>
			<div class="col-6">
				<h3 class="big-bold">{{ hot_product.name}}</h3>
				<h3 class="red">горячее предложение</h3>
				<p class="price">{{ hot_product.price }} <span>руб</span></p>
				<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					{{ hot_product.description }}
				</div>
			</div>
		</div>
        <h2>
            Категория: {{ category.name }}
        </h2>
		<div class="paginator">
			{% if products.has_previous %}
			<a href="{% url 'products:page' category.pk products.previous_page_number %}">
			<
			</a>
				{% endif %}
			<span class="current">
				страница {{ products.number }} из {{products.paginator.num_pages }}
			</span>

			{% if products.has_next %}
			<a href="{% url 'products:page' category.pk products.next_page_number %}">
			>
			</a>
				{% endif %}
		</div>

        <div class="category-products row">
            {% for product in products %}
              <div class="block w-25 my-3 mx-3">
                <a href="{% url 'products:product' product.pk %}">
                  <img src="/media/{{ product.image }}" alt="{{product.short_desc}}">
                  <div class="text">
                    <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                      <h4>{{ product.name }}</h4>
                      <p>{{ product.description }}</p>
                  </div>
                </a>
              </div>
            {% endfor %}
        </div>
		<div class="related">
			<div class="title clearfix">
				<h2>Похожие продукты</h2>
				<a class="explore" href="#">показать все <img src="{%static 'img/arrow.png'%}" alt=""></a>
			</div>
			<div class="related-products clearfix">
				<div class="block">
					<a href="#"><img src="{%static 'img/product-11.jpg'%}" alt="">
						<div class="text">
							<img src="{%static 'img/icon-hover.png'%}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{%static 'img/product-21.jpg'%}" alt="">
						<div class="text">
							<img src="{%static 'img/icon-hover.png'%}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{%static 'img/product-31.jpg'%}" alt="">
						<div class="text">
							<img src="{%static 'img/icon-hover.png'%}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>

			</div>
		</div>
	</div>
		</div>

{% endblock %}